// AUTO-GENERATED by 13a-rules-db's scripts/generate-archmage-setup.mjs
// from data/2e/classes/*.yaml's `archmage_class_config` blocks —
// do not hand-edit, re-run the generator instead. Registers classes
// archmage doesn't know about into CONFIG.ARCHMAGE at the ready hook, the
// same technique the dark-pacts-13th-age (2e) reference module uses.
//
// NOTE: keyModifiers pairs are written from every class's own perspective
// (both directions), not archmage's own base-game "alphabetical lower
// triangle, store once" convention — simpler and harmless, since the
// registration order here can't be assumed to match core's.
Hooks.on("ready", function () {
  console.log("Abomination (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["abomination2e"] = "Abomination";
  CONFIG.ARCHMAGE.classes["abomination2e"] = {"hp":8,"ac_lgt":13,"ac_hvy":15,"ac_hvy_pen":-5,"shld_pen":-2,"pd":11,"md":10,"rec_die":10,"wpn_1h":8,"wpn_2h":10,"wpn_2h_pen":-1,"wpn_rngd":6,"skilled_warrior":true};
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["barbarian"] = ["str","con"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["bard"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["chaosmage"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["cleric"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["commander"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["druid"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["fighter"] = ["str","con"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["monk"] = ["dex","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["necromancer"] = ["int","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["occultist"] = ["int","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["paladin"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["ranger"] = ["dex","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["rogue"] = ["dex","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["sorcerer"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination2e"]["wizard"] = ["str","int"];
  console.log("Abomination (13th Age) class loaded successfully.");

  console.log("Fateweaver (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["fateweaver2e"] = "Fateweaver";
  CONFIG.ARCHMAGE.classes["fateweaver2e"] = {"hp":5,"ac_lgt":10,"ac_hvy":11,"ac_hvy_pen":-2,"shld_pen":-1,"pd":10,"md":11,"rec_die":6,"wpn_1h":6,"wpn_2h":8,"wpn_2h_pen":-2,"wpn_rngd":6,"skilled_warrior":false};
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["abomination2e"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["barbarian"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["bard"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["chaosmage"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["cleric"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["commander"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["druid"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["fighter"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["monk"] = ["dex","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["necromancer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["occultist"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["paladin"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["ranger"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["rogue"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["sorcerer"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver2e"]["wizard"] = ["int","wis"];
  console.log("Fateweaver (13th Age) class loaded successfully.");

  console.log("Psion (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["psion2e"] = "Psion";
  CONFIG.ARCHMAGE.classes["psion2e"] = {"hp":6,"ac_lgt":10,"ac_hvy":11,"ac_hvy_pen":-2,"shld_pen":0,"pd":9,"md":9,"rec_die":6,"wpn_1h":6,"wpn_2h":8,"wpn_2h_pen":0,"wpn_rngd":6,"skilled_warrior":false};
  CONFIG.ARCHMAGE.keyModifiers["psion2e"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["abomination2e"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["barbarian"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["bard"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["chaosmage"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["cleric"] = ["wis","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["commander"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["druid"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["fateweaver2e"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["fighter"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["monk"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["necromancer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["occultist"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["paladin"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["ranger"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["rogue"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["sorcerer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion2e"]["wizard"] = ["int","con"];
  CONFIG.ARCHMAGE.classResources["psion2e"] = [["PP","quick"]];
  console.log("Psion (13th Age) class loaded successfully.");

  console.log("Savage (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["savage2e"] = "Savage";
  CONFIG.ARCHMAGE.classes["savage2e"] = {"hp":8,"ac_lgt":12,"ac_hvy":13,"ac_hvy_pen":-2,"shld_pen":0,"pd":11,"md":10,"rec_die":10,"wpn_1h":8,"wpn_2h":10,"wpn_2h_pen":0,"wpn_rngd":8,"skilled_warrior":true};
  CONFIG.ARCHMAGE.keyModifiers["savage2e"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["abomination2e"] = ["str","con"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["barbarian"] = ["str","con"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["bard"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["chaosmage"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["cleric"] = ["wis","str"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["commander"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["druid"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["fateweaver2e"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["fighter"] = ["con","str"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["monk"] = ["str","dex"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["necromancer"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["occultist"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["paladin"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["psion2e"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["ranger"] = ["dex","str"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["rogue"] = ["str","dex"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["sorcerer"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage2e"]["wizard"] = ["int","str"];
  CONFIG.ARCHMAGE.classResources["savage2e"] = [["Frenzydice","quickreset"],["Frenzydiesize","none"]];
  console.log("Savage (13th Age) class loaded successfully.");

  console.log("Swordmage (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["swordmage2e"] = "Swordmage";
  CONFIG.ARCHMAGE.classes["swordmage2e"] = {"hp":7,"ac_lgt":13,"ac_hvy":14,"ac_hvy_pen":-2,"shld_pen":-2,"pd":10,"md":10,"rec_die":8,"wpn_1h":8,"wpn_2h":10,"wpn_2h_pen":0,"wpn_rngd":8,"skilled_warrior":true};
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["abomination2e"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["barbarian"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["bard"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["chaosmage"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["cleric"] = ["wis","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["commander"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["druid"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["fateweaver2e"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["fighter"] = ["int","str"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["monk"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["necromancer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["occultist"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["paladin"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["psion2e"] = ["int","con"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["ranger"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["rogue"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["savage2e"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["sorcerer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage2e"]["wizard"] = ["int","con"];
  console.log("Swordmage (13th Age) class loaded successfully.");

  console.log("Warlock (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["warlock2e"] = "Warlock";
  CONFIG.ARCHMAGE.classes["warlock2e"] = {"hp":6,"ac_lgt":11,"ac_hvy":12,"ac_hvy_pen":-2,"shld_pen":0,"pd":11,"md":11,"rec_die":6,"wpn_1h":8,"wpn_2h":10,"wpn_2h_pen":0,"wpn_rngd":8,"skilled_warrior":false};
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["abomination2e"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["barbarian"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["bard"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["chaosmage"] = ["con","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["cleric"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["commander"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["druid"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["fateweaver2e"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["fighter"] = ["cha","str"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["monk"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["necromancer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["occultist"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["paladin"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["psion2e"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["ranger"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["rogue"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["savage2e"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["sorcerer"] = ["con","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["swordmage2e"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock2e"]["wizard"] = ["int","cha"];
  console.log("Warlock (13th Age) class loaded successfully.");
});
