// AUTO-GENERATED by 13a-rules-db's scripts/generate-archmage-setup.mjs
// from data/2e/classes/*.yaml's `archmage_class_config` blocks —
// do not hand-edit, re-run the generator instead. Registers classes
// archmage doesn't know about into CONFIG.ARCHMAGE at the ready hook, the
// same technique the dark-pacts-13th-age (2e) reference module uses.
//
// NOTE: keyModifiers pairs are written from every class's own perspective
// (both directions), not archmage's own base-game "alphabetical lower
// triangle, store once" convention — simpler and harmless, since the
// registration order here can't be assumed to match core's.
Hooks.on("ready", function () {
  // Without this, archmage's Import Powers dialog never shows this
  // module's own class journal (level table, etc.) for ANY of the
  // classes below — see this generator's own comment for why.
  CONFIG.ARCHMAGE.classPacks ??= [];
  if (!CONFIG.ARCHMAGE.classPacks.includes("classes-2e")) {
    CONFIG.ARCHMAGE.classPacks.push("classes-2e");
  }

  console.log("Abomination (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["abomination"] = "Abomination";
  CONFIG.ARCHMAGE.classes["abomination"] = {"hp":8,"ac_lgt":13,"ac_hvy":15,"ac_hvy_pen":-5,"shld_pen":-2,"pd":11,"md":10,"rec_die":10,"wpn_1h":8,"wpn_2h":10,"wpn_2h_pen":-1,"wpn_rngd":6,"skilled_warrior":true};
  CONFIG.ARCHMAGE.keyModifiers["abomination"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["barbarian"] = ["str","con"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["bard"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["chaosmage"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["cleric"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["commander"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["druid"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["fighter"] = ["str","con"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["monk"] = ["dex","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["necromancer"] = ["int","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["occultist"] = ["int","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["paladin"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["ranger"] = ["dex","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["rogue"] = ["dex","str"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["sorcerer"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["abomination"]["wizard"] = ["str","int"];
  console.log("Abomination (13th Age) class loaded successfully.");

  console.log("Fateweaver (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["fateweaver"] = "Fateweaver";
  CONFIG.ARCHMAGE.classes["fateweaver"] = {"hp":5,"ac_lgt":10,"ac_hvy":11,"ac_hvy_pen":-2,"shld_pen":-1,"pd":10,"md":11,"rec_die":6,"wpn_1h":6,"wpn_2h":8,"wpn_2h_pen":-2,"wpn_rngd":6,"skilled_warrior":false};
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["abomination"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["barbarian"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["bard"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["chaosmage"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["cleric"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["commander"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["druid"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["fighter"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["monk"] = ["dex","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["necromancer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["occultist"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["paladin"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["ranger"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["rogue"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["sorcerer"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["fateweaver"]["wizard"] = ["int","wis"];
  console.log("Fateweaver (13th Age) class loaded successfully.");

  console.log("Psion (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["psion"] = "Psion";
  CONFIG.ARCHMAGE.classes["psion"] = {"hp":6,"ac_lgt":10,"ac_hvy":11,"ac_hvy_pen":-2,"shld_pen":0,"pd":9,"md":9,"rec_die":6,"wpn_1h":6,"wpn_2h":8,"wpn_2h_pen":0,"wpn_rngd":6,"skilled_warrior":false};
  CONFIG.ARCHMAGE.keyModifiers["psion"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["psion"]["abomination"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["barbarian"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["bard"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["chaosmage"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["cleric"] = ["wis","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["commander"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["druid"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["fateweaver"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["fighter"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["monk"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["necromancer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["occultist"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["paladin"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["ranger"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["rogue"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["sorcerer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["psion"]["wizard"] = ["int","con"];
  CONFIG.ARCHMAGE.classResources["psion"] = [["PP","quick"]];
  console.log("Psion (13th Age) class loaded successfully.");

  console.log("Savage (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["savage"] = "Savage";
  CONFIG.ARCHMAGE.classes["savage"] = {"hp":8,"ac_lgt":12,"ac_hvy":13,"ac_hvy_pen":-2,"shld_pen":0,"pd":11,"md":10,"rec_die":10,"wpn_1h":8,"wpn_2h":10,"wpn_2h_pen":0,"wpn_rngd":8,"skilled_warrior":true};
  CONFIG.ARCHMAGE.keyModifiers["savage"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["savage"]["abomination"] = ["str","con"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["barbarian"] = ["str","con"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["bard"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["chaosmage"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["cleric"] = ["wis","str"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["commander"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["druid"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["fateweaver"] = ["str","wis"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["fighter"] = ["con","str"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["monk"] = ["str","dex"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["necromancer"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["occultist"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["paladin"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["psion"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["ranger"] = ["dex","str"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["rogue"] = ["str","dex"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["sorcerer"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["savage"]["wizard"] = ["int","str"];
  CONFIG.ARCHMAGE.classResources["savage"] = [["Frenzydice","quickreset"],["Frenzydiesize","none"]];
  console.log("Savage (13th Age) class loaded successfully.");

  console.log("Swordmage (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["swordmage"] = "Swordmage";
  CONFIG.ARCHMAGE.classes["swordmage"] = {"hp":7,"ac_lgt":13,"ac_hvy":14,"ac_hvy_pen":-2,"shld_pen":-2,"pd":10,"md":10,"rec_die":8,"wpn_1h":8,"wpn_2h":10,"wpn_2h_pen":0,"wpn_rngd":8,"skilled_warrior":true};
  CONFIG.ARCHMAGE.keyModifiers["swordmage"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["abomination"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["barbarian"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["bard"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["chaosmage"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["cleric"] = ["wis","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["commander"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["druid"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["fateweaver"] = ["int","wis"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["fighter"] = ["int","str"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["monk"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["necromancer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["occultist"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["paladin"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["psion"] = ["int","con"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["ranger"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["rogue"] = ["dex","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["savage"] = ["str","int"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["sorcerer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["swordmage"]["wizard"] = ["int","con"];
  console.log("Swordmage (13th Age) class loaded successfully.");

  console.log("Warlock (13th Age) class injecting data into the system...");
  CONFIG.ARCHMAGE.classList["warlock"] = "Warlock";
  CONFIG.ARCHMAGE.classes["warlock"] = {"hp":6,"ac_lgt":11,"ac_hvy":12,"ac_hvy_pen":-2,"shld_pen":0,"pd":11,"md":11,"rec_die":6,"wpn_1h":8,"wpn_2h":10,"wpn_2h_pen":0,"wpn_rngd":8,"skilled_warrior":false};
  CONFIG.ARCHMAGE.keyModifiers["warlock"] ??= {};
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["abomination"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["barbarian"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["bard"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["chaosmage"] = ["con","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["cleric"] = ["wis","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["commander"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["druid"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["fateweaver"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["fighter"] = ["cha","str"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["monk"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["necromancer"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["occultist"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["paladin"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["psion"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["ranger"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["rogue"] = ["dex","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["savage"] = ["str","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["sorcerer"] = ["con","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["swordmage"] = ["int","cha"];
  CONFIG.ARCHMAGE.keyModifiers["warlock"]["wizard"] = ["int","cha"];
  console.log("Warlock (13th Age) class loaded successfully.");
});
